Enhance LDAP documentation
netbox-community/netbox pull request #1080
Opened 2017-04-13 21:05 UTC by bellwood

Incorporating @marvnrawley LDAP enhancements from #518

2017-05-08 21:52 UTC, Carbenium approved these changes
LDAP user here.

I can't comment on the Windows part since we use FreeIPA. The rest is a great explanation of the mappings.

2017-05-14 13:05 UTC, adamtbeames commented
I'm still not able to get Windows LDAP working.
Some some pointers in the doc about how to debug would be very helpful.

2017-05-17 19:17 UTC, jeremystretch requested changes

2017-05-17 19:17 UTC, jeremystretch commented on docs/installation/ldap.md
> +    "is_active" - you must map all users to at least this group if you want their account to be treated as enabled. Without this, your users cannot log in.
Please capitalize the first word in each sentence for these descriptions

2017-05-17 19:17 UTC, jeremystretch commented on docs/installation/ldap.md
> +AUTH_LDAP_USER_ATTR_MAP = {
Probably want to wrap this in a code block and ensure proper indentation

2017-05-31 18:46 UTC, jeremystretch commented
Pinging @bellwood - Are you available to make these changes?

2017-05-31 18:48 UTC, bellwood commented
Been burried lately - will attempt to get a revised PR this week

2017-06-06 00:37 UTC, bellwood commented
Sorry for the late edits on this - been all over the place lately

Thanks for the feedback =)

2017-06-08 13:55 UTC, merged