12489 Use HTMX for Location and Non-Racked Devices in Site detail view
netbox-community/netbox pull request #12491
Opened 2023-05-04 21:44 UTC by arthanson

### Fixes: #12489 

Changes site view to use HTMX for Locations and Non-Racked Devices in Site detail view. See before and after screenshots below.  Also removed the now unused queries from the view.

![Monosnap MDF | NetBox 2023-05-04 14-39-25](https://user-images.githubusercontent.com/99642/236336265-8e10e493-b767-41ae-8800-85d2d55ccd27.png)
![Monosnap MDF | NetBox 2023-05-04 14-39-56](https://user-images.githubusercontent.com/99642/236336271-cf609d09-0df0-4915-9b95-a0903de11599.png)

2023-05-05 12:35 UTC, jeremystretch commented on netbox/templates/dcim/inc/nonracked_devices.html
This template file is used by the rack and location views as well, so we can't make changes to it unless those views are also updated. Instead, we could just copy the new content directly into `site.html` and remove the include from that template.

2023-05-05 15:11 UTC, arthanson commented on netbox/templates/dcim/inc/nonracked_devices.html
updated rack and location templates as well.

2023-05-12 13:33 UTC, jeremystretch requested changes

2023-05-15 20:28 UTC, arthanson commented on netbox/templates/dcim/rack.html
> +                hx-get="{% url 'dcim:device_list' %}?rack_id={{ object.pk }}&position=null&parent_bay_id=null"
went with adding has_position filter.

2023-08-28 18:55 UTC, jeremystretch commented on netbox/dcim/filtersets.py
> +    has_position = django_filters.BooleanFilter(
We shouldn't need to introduce a new filter for this; the `position` filter should support a null (empty) lookup. I've opened #13585 to address this.

2023-08-28 20:03 UTC, merged