DRAFT: 12175 rack with starting unit > 1
netbox-community/netbox pull request #12778
Opened 2023-05-31 19:52 UTC by arthanson

### Fixes: #12175

2023-05-31 19:54 UTC, arthanson commented
@jeremystretch this one is blocked on https://github.com/netbox-community/netbox/pull/12632 as I'd like to use the TrackingModelMixin from that PR in order to track changes to the starting_unit as it needs to update all devices in the rack if that is changed.

2023-06-21 20:18 UTC, jeremystretch requested changes
Nice work!

2023-06-21 20:18 UTC, jeremystretch commented on netbox/dcim/models/racks.py
> +            ).order_by('position').first()
We should be able to reuse the above queryset and just call `first()` and `last()` to get the top and bottom devices, respectively.

2023-06-21 20:18 UTC, jeremystretch commented on netbox/dcim/models/racks.py
> +            # Validate the Rack starting_unit > position of any installed devices
```suggestion
            # Validate that the Rack's starting_unit is <= the position of the lowest mounted device (if any)
```

2023-06-21 20:18 UTC, jeremystretch commented on netbox/dcim/models/racks.py
> +            return drange(decimal.Decimal(self.starting_unit), self.u_height + 1, 0.5)
This fixes the unit list for racks with descending unit numbering.

```suggestion
            return drange(decimal.Decimal(self.starting_unit), self.u_height + self.starting_unit, 0.5)
```

2023-06-22 13:09 UTC, merged