Fixes #12847 - Include Missing Add buttons to Views
netbox-community/netbox pull request #12864
Opened 2023-06-11 20:10 UTC by sudheesh001

### Fixes: #12847 

- Includes missing `Add` button in Views for `Device Components`
- Includes missing `Add` button in Views for `Virtualization > Interfaces`

2023-06-13 13:02 UTC, jeremystretch requested changes

2023-06-14 17:07 UTC, sudheesh001 commented
Thanks for the review @jeremystretch I just updated the PR based on your feedback. Please let me know if this would be a better patch.

2023-06-14 17:32 UTC, jeremystretch commented
That'll work, thanks!

2023-06-14 17:33 UTC, jeremystretch approved these changes

2023-06-14 17:33 UTC, merged