DRAFT: 12589 move user and group admin from admin
netbox-community/netbox pull request #12877
Opened 2023-06-12 23:03 UTC by arthanson

### Fixes: #12589

2023-07-11 16:01 UTC, jeremystretch requested changes
Thanks for taking this on! It seems like we need to more clearly separate the general-purpose user functions (which were migrated from the admin UI) from the _user-specific_ views (profile, password change, etc.). These should not use the same base template.

2023-07-13 11:30 UTC, arthanson commented on netbox/templates/users/password.html
> +{% extends 'users/base_profile.html' %}
added.

2023-07-13 11:31 UTC, arthanson commented on netbox/templates/users/base.html
> -{% endblock %}
This was moved to base_profile.html to make separate base templates for the user and profile stuff.

2023-07-13 11:34 UTC, arthanson commented on netbox/users/forms/model_forms.py
> +                except FieldError as e:
done

2023-07-13 11:59 UTC, arthanson commented on netbox/users/tables.py
> +    username = tables.LinkColumn('users:netboxuser', args=[A('pk')])
done

2023-07-13 11:59 UTC, arthanson commented on netbox/users/tables.py
> +    name = tables.LinkColumn('users:netboxgroup', args=[A('pk')])
done

2023-07-13 12:00 UTC, arthanson commented on netbox/users/tables.py
> +    name = tables.LinkColumn('users:objectpermission', args=[A('pk')])
done

2023-07-14 04:24 UTC, arthanson commented on netbox/users/forms/model_forms.py
> +    object_types = forms.ModelMultipleChoiceField(
done

2023-07-20 20:22 UTC, merged