Add Brazilian power outlet standard to choices.py
netbox-community/netbox pull request #13012
Opened 2023-06-26 19:52 UTC by BrunoBlanes

### Fixes: #13009

Add 10A and 20A plugs standardized by the Brazilian Association of Technical Standards.

2023-06-27 13:09 UTC, DanSheps requested changes

2023-06-27 13:21 UTC, BrunoBlanes commented on netbox/dcim/choices.py
> +        ('NBR 14136', (
This makes sense, we can group all plug types derived from this IEC to make it clearer.

2023-07-06 12:52 UTC, jeremystretch commented
This defines the outlet (female) types but not the port (male) types. @BrunoBlanes could you add those too please?

2023-07-06 14:04 UTC, BrunoBlanes commented
> This defines the outlet (female) types but not the port (male) types. @BrunoBlanes could you add those too please?

Sure.

2023-07-28 13:25 UTC, jeremystretch commented
To be honest I'm not 100% on the "2P+T" descriptor as I don't see it documented anywhere, but I'll defer to @BrunoBlanes as a regional user who is no doubt more familiar with the standard.

2023-07-28 13:26 UTC, merged

2023-07-28 15:09 UTC, BrunoBlanes commented
> To be honest I'm not 100% on the "2P+T" descriptor as I don't see it documented anywhere, but I'll defer to @BrunoBlanes as a regional user who is no doubt more familiar with the standard.

It does not show up as an acronym on the standard, but vendors did make a good effort of putting it everywhere on their products to the point that it has become a standard itself.

2023-07-28 15:11 UTC, jeremystretch commented
Thanks @BrunoBlanes!