Fixes #13477 - Correct filter name in redirect after bulk edit
netbox-community/netbox pull request #13491
Opened 2023-08-17 07:31 UTC by kkthxbye-code

### Fixes: #13477

Makes create_and_update_objects return an extra bool indicating if the operation was creation or updating. Uses this bool to choose the correct filter.

2023-08-17 12:55 UTC, jeremystretch requested changes

2023-08-17 12:59 UTC, kkthxbye-code commented on netbox/netbox/views/generic/bulk_views.py
> +        return saved_objects, is_update
I wasn't even aware that both were supported in the same inport, I'll take another look at it.

2023-08-17 13:01 UTC, jeremystretch commented on netbox/netbox/views/generic/bulk_views.py
> +        return saved_objects, is_update
Well, I only know it's _possible_. I don't know if it's _supported_. :slightly_smiling_face:

2023-08-18 06:26 UTC, kkthxbye-code commented on netbox/netbox/views/generic/bulk_views.py
> +        return saved_objects, is_update
I added `modified_by_request` and changed the redirect to use this filter. It finds both update and create changes. I don't think  deletions make any sense as filtering an query looking for deleted objects is bound to always return nothing 😄

2023-08-21 18:34 UTC, jeremystretch commented
Thanks @kkthxbye-code!

2023-08-21 18:35 UTC, merged