Add bulk (CSV) import/export for more object types
netbox-community/netbox pull request #1359
Opened 2017-07-18 02:13 UTC by paravoid

### Fixes: 1347

This adds bulk (CSV) import & export for regions, rack groups, manufacturers and device types, which can be useful when e.g. importing from a legacy system, as described in #1347. 

Mostly copy/paste from the bulk/CSV forms of other object types and tested locally with a few fields for each (but not all), so a careful code review would be appropriate and appreciated!

2017-07-18 19:28 UTC, jeremystretch requested changes
Looks good! Just a couple minor tweaks and we can merge this. Thanks!

2017-07-18 19:28 UTC, jeremystretch commented on netbox/dcim/forms.py
> +    parent = forms.ModelChoiceField(
This should probably be a `TreeNodeChoiceField` from `mptt.forms`.

2017-07-18 19:28 UTC, jeremystretch commented on netbox/dcim/forms.py
> +
Can omit blank lines between model fields

2017-07-18 19:28 UTC, jeremystretch commented on netbox/dcim/forms.py
> +    interface_ordering = CSVChoiceField(
Can add `required=False` here as the field has a default value.

2017-07-18 19:28 UTC, jeremystretch commented on netbox/dcim/models.py
> +            self.parent if self.parent else None,
Should probably be `self.parent.name`

2017-07-18 19:28 UTC, jeremystretch commented on netbox/dcim/models.py
> +            self.manufacturer,
`self.manufacturer.name` just to be explicit

2017-07-18 19:28 UTC, jeremystretch commented on netbox/dcim/models.py
> +            self.get_interface_ordering_display() if self.interface_ordering else None,
Just `self.get_interface_ordering_display()`: `interface_ordering` is a required field

2017-07-25 14:13 UTC, paravoid commented on netbox/dcim/forms.py
> +    parent = forms.ModelChoiceField(
Not sure -- in my setup where I have a region "Europe", another one "US", with children "US East" and "US West", with this change it shows as:
```
Name of parent region
Choices: Europe, US, --- US East, etc. 
```
…while before this change it shows up as:
```
 Name of parent region
Choices: Europe, US, US East, etc. 
```

2017-08-01 19:30 UTC, jeremystretch commented on netbox/dcim/forms.py
> +    parent = forms.ModelChoiceField(
Ah, good point.

2017-08-03 19:15 UTC, jeremystretch approved these changes

2017-08-16 08:57 UTC, paravoid commented
This was approved but not merged ­-- was that intentional? Anything I can do?

2017-08-16 13:47 UTC, jeremystretch commented
@paravoid Could you resolve the conflicts in the base template please? Sorry, I had made some style changes. Other than that I've just been waiting to get to a point where I can implement the rest of the imports.

2017-09-29 16:35 UTC, merged