Fixes #13666: Fix behavior for reports without test methods
netbox-community/netbox pull request #13667
Opened 2023-09-03 11:31 UTC by JCWasmx86

### Fixes: #13666

If you upload a report file without any test methods, the entire GUI for the reports page fails. This fixes the error by splitting up the `report_modules` into valid and empty ones. The valid `report_module`s are rendered as before, the empty ones are listed with the possibility to delete them. (Before you had to drop into the CLI to delete them)

The list of reports without test methods are at the top of the page to increase the visibility of them, but you could consider moving them into the normal list of reports, but show an error/warning there - similar to e.g. "Failed to load foo.py"

2023-09-25 17:50 UTC, jeremystretch requested changes
A much simpler fix would be to simply remove the exception (below) and perhaps add a warning to the UI when viewing a report with no test methods. (It might also make sense to disable the "run" action.)

https://github.com/netbox-community/netbox/blob/0ce2b1b779228befa55d867eacb863b7f2ee1684/netbox/extras/reports.py#L109-L110

2023-09-25 19:12 UTC, JCWasmx86 commented
Yes I will do that. I hesitated to remove the exception, as I thought it was maybe important (And just not documented, why missing test methods should be an error instead of an warning - thus this more complex solution)

2023-09-26 07:02 UTC, JCWasmx86 commented
Do you like a design like that:

![image](https://github.com/netbox-community/netbox/assets/63594136/a7df1435-afa9-4177-ad10-3aea69857bfe)

Or should the alert be an entire table row below the ReportClass?

2023-09-26 13:03 UTC, jeremystretch commented
I would change the text to something like "Invalid (no test methods found)" and remove the alert styling (it's not intended for table cells). But otherwise yes I think this is great!

2023-09-26 13:29 UTC, JCWasmx86 commented
Looks like that now:

![image](https://github.com/netbox-community/netbox/assets/63594136/128159b2-3480-4800-b3bc-86076fc116ac)


The button here is now disabled:

![image](https://github.com/netbox-community/netbox/assets/63594136/fa1ff8c2-9ae5-4eb4-8033-2e6ef372328c)

2023-09-26 14:20 UTC, jeremystretch approved these changes
Thanks @JCWasmx86!

2023-09-26 14:41 UTC, merged