13745 device type migration
netbox-community/netbox pull request #13747
Opened 2023-09-12 20:16 UTC by arthanson

### Fixes: #13745 

Optimize counter field migration on DeviceType for large databases.

2023-09-13 12:36 UTC, jeremystretch commented
While this addresses the immediate concern, I'd argue that we should utilize the same approach for all three affected migrations (`dcim.0176_device_component_counters` and `virtualization.0035_virtualmachine_interface_count` as well).

Also, we probably want to move the logic from the management command somewhere internally so that it be can be reused by the migrations.

2023-09-13 12:53 UTC, jeremystretch requested changes
While this addresses the immediate concern, I'd argue that we should utilize the same approach for all three affected migrations (`dcim.0176_device_component_counters` and `virtualization.0035_virtualmachine_interface_count` as well).

Also, we probably want to move the logic from the management command (rather than duplicating it) somewhere internally so that it be can be reused by the migrations.

2023-09-13 15:33 UTC, arthanson commented
> While this addresses the immediate concern, I'd argue that we should utilize the same approach for all three affected migrations (`dcim.0176_device_component_counters` and `virtualization.0035_virtualmachine_interface_count` as well).
> 
> Also, we probably want to move the logic from the management command (rather than duplicating it) somewhere internally so that it be can be reused by the migrations.

Moved the calculate routine to utilities then updated all migrations to use this pattern.

2023-09-18 13:59 UTC, jeremystretch approved these changes

2023-09-18 13:59 UTC, merged