Attached a clonable field multi selection, bug fixes
netbox-community/netbox pull request #13935
Opened 2023-09-29 06:51 UTC by yash-pal1

### Fixes: #13909

2023-09-29 07:30 UTC, abhi1693 commented on netbox/utilities/forms/fields/dynamic.py
> +                choice for choice in self.choices if isinstance(self.choices, str) if choice[0] in data
```suggestion
                choice for choice in self.choices if isinstance(self.choices, str) and choice[0] in data
```

I think `and` should suffice here

2023-10-03 19:03 UTC, jeremystretch requested changes
While this avoids the exception, it doesn't actually fix the cloning functionality. The new form should be pre-populated with the custom field value(s) from the object being cloned.

2023-10-30 12:25 UTC, jeremystretch commented
@yash-pal1 are you still interested in working on this?

2023-10-30 12:31 UTC, yash-pal1 commented
> @yash-pal1 are you still interested in working on this?



> @yash-pal1 are you still interested in working on this?

trying to fix this, so sorry for not active on this issue

2023-12-27 19:22 UTC, jeremystretch commented
Closing for inactivity. Please see #14612 for a (very similar) alternative fix.

2023-12-27 19:22 UTC, closed without merging