Enhance Virtual Machine and Device Platform Filter with Manufacturer Information
netbox-community/netbox pull request #14047
Opened 2023-10-16 14:08 UTC by kprince28

### Fixes: #12741

2023-10-17 13:03 UTC, jeremystretch requested changes

2023-10-17 13:03 UTC, jeremystretch commented on netbox/virtualization/forms/filtersets.py
> +    )
There is no `manufacturer_id` filter for virtual machines, so this form field would have no effect beyond constraining the choices for the platform field below, which could be very confusing to the user. The scope of FR #12741 deals only with the VM & device edit forms; we shouldn't be making any changes to the list filters as part of this work anyway.

2023-10-31 14:15 UTC, kprince28 commented on netbox/virtualization/forms/model_forms.py
> +    )
@jeremystretch,
I'm curious about the `Advanced Selector Widget` and how it operates. Have you had the opportunity to implement it in your code? If so, I'd highly appreciate it if you could provide some references or perhaps share a few examples. Your expertise and insights would be immensely helpful in enhancing my understanding of this widget.

2023-10-31 14:19 UTC, DanSheps commented on netbox/virtualization/forms/model_forms.py
> +    )
You remove `initial_params={}` and instead use `selector=True`

2023-11-02 14:52 UTC, DanSheps approved these changes

2023-11-09 14:55 UTC, jeremystretch commented
Thanks @kprince28!

2023-11-09 14:55 UTC, merged