14424 Remove ChangeLoggedModel from StagedChange
netbox-community/netbox pull request #14476
Opened 2023-12-08 16:23 UTC by arthanson

### Fixes: #14424 

Remove ChangeLoggedModel from StagedChange.  Not sure of the testing to do for this beyond the test suites.

2023-12-08 20:54 UTC, jeremystretch requested changes

2023-12-08 20:54 UTC, jeremystretch commented on netbox/extras/migrations/0104_remove_stagedchange_created_and_more.py
Let's give the migration a meaningful name; something like `0104_stagedchange_remove_change_logging`.

2023-12-08 22:28 UTC, arthanson commented on netbox/extras/migrations/0104_remove_stagedchange_created_and_more.py
Done

2023-12-11 15:49 UTC, jeremystretch approved these changes

2023-12-11 15:50 UTC, merged