Add interfaces CSV import, interfaces list, and import/export buttons to device
netbox-community/netbox pull request #1465
Opened 2017-09-01 08:32 UTC by netsiphon

Fixes: #1347 Bulk CSV import for more object types

If you would prefer I can open a feature request/requests specifically for these changes under my name and resubmit. Apologize for all of the tiny commits...netbox dev running on non-local vm and I'm a Django novice.

Proposed changes:

1. Add Import Interfaces CSV form
2. Add Interfaces List form to allow search and filtering for export
3. Add Import and Export Interfaces buttons to Device view with direct link to Interface List form export(for specific device).

2017-10-24 19:16 UTC, netsiphon commented
Besides resolving the conflicts with base.html can I do anything else to make these changes includable? Is it a matter of project roadmap or my implementation?

2017-10-31 17:10 UTC, jeremystretch requested changes
I appreciate the effort, but there's a lot of stuff in here that needs to be reworked or simply isn't needed. Primarily, we don't want to introduce a view which lists interfaces on their own; like other components, interfaces should normally only be shown within the context of their parent device. Also, please review the data model for interfaces: You've introduced several fields in the import form which do not correspond to database fields.

2017-10-31 17:10 UTC, jeremystretch commented on netbox/dcim/constants.py
> +IFACE_DISABLED = False
`enabled` is a boolean field; no need for constants.

2017-10-31 17:10 UTC, jeremystretch commented on netbox/dcim/filters.py
> +class InterfaceListFilter(django_filters.FilterSet):
We already have an `InterfaceFilter` class.

2017-10-31 17:10 UTC, jeremystretch commented on netbox/dcim/forms.py
> +    is_virtual = forms.BooleanField(
None of the `is_*` properties are database fields.

2017-10-31 17:10 UTC, jeremystretch commented on netbox/dcim/urls.py
> +    url(r'^interfaces/$', views.InterfaceListView.as_view(), name='interface_list'),
There's no need for a view which exposes device components outside the context of a device.

2017-11-15 17:56 UTC, closed without merging

2017-11-15 19:03 UTC, netsiphon commented
Sorry I haven't been able to get back to this...I think before I rework the changes, I'll have to convince you of the need for an interfaces view if only for use in filtering interface exports and also for searching through interface information all in one place.  

I believe you said elsewhere that the description field is populated from ifDescr through napalm, but we've attempted to use it for label information when it comes to patch panels far end connections.

I suppose we could define wall plates as devices and give them interfaces, then make the interface connections but that will create a tremendous number of devices and still require us to export interfaces for multiple devices at the same time. Also, it would be good to be able to populate a db field for the ifAlias field as we often try to put far end connections into the device configuration but that could be for another day.

2017-11-15 19:11 UTC, jeremystretch commented
> I believe you said elsewhere that the description field is populated from ifDescr through napalm

NetBox does not populate anything via NAPALM. NAPALM is only used to validate live data against what has been administratively defined in NetBox.

> but we've attempted to use it for label information when it comes to patch panels far end connections

NetBox doesn't yet support modeling a physical cable plant (see #20).

2017-11-15 19:40 UTC, netsiphon commented
Ok, keeping physical devices out of it as I see the disclaimer.

So you would incorporate the interface import view(with fixes) allowing import from any number of devices but export only if it is limited to the single device view alone yes? Is the search or export of interfaces based on a filter something you would want to limit to a report or backend db access?

I ask because we still have chassis devices with 500+ interfaces so even visually searching within the same device isn't necessarily quick.