DRAFT: 14729 Move background tasks list from admin UI to Primary UI
netbox-community/netbox pull request #14825
Opened 2024-01-17 17:26 UTC by arthanson

### Fixes: #14729 

Adds list and drill-down to detail view for RQ queues:

![Monosnap Background Tasks | NetBox 2024-01-17 07-52-17](https://github.com/netbox-community/netbox/assets/99642/dd0a67ae-b7f5-4c48-9438-b18288c33a88)
![Monosnap Job | NetBox 2024-01-17 09-24-53](https://github.com/netbox-community/netbox/assets/99642/695b88ee-5e00-4fa8-ba2b-0c886e305e57)
![Monosnap Queued Jobs in default | NetBox 2024-01-17 07-52-31](https://github.com/netbox-community/netbox/assets/99642/3b89baa9-c775-41dd-97b7-4ee206c82084)

2024-01-17 20:40 UTC, jeremystretch requested changes
Thanks @arthanson! I haven't really looked at the templates yet as I know they'll need updating for #12128 anyway.

2024-01-17 20:40 UTC, jeremystretch commented on netbox/core/tables/tasks.py
> +    started_jobs = tables.Column(verbose_name=_("Active Jobs"))
We need to be more careful about using "tasks" versus "jobs." This view is showing RQ tasks, and the column headers should reflect that. (IMO it's reasonable to omit the second word and just show e.g. "Active" or "Deferred.")

2024-01-17 20:40 UTC, jeremystretch commented on netbox/core/tables/tasks.py
> +    def render_id(self, value, record):
Hyperlinks should be handled by passing `linkify` to the column. This ensures that the raw data remains available for clean export.

2024-01-17 20:40 UTC, jeremystretch commented on netbox/core/urls.py
> +    path('background-tasks/queues/<int:queue_index>/<str:job_id>/', views.BackgroundTasksJobDetailView.as_view(), name='background_tasks_job_detail'),
We can simplifying the URL tree a bit:

* `background-queues/` - Queue list
* `background-queues/<id>/` - Tasks list for a specific queue
* `background-tasks/<id>/` - Task detail view

2024-01-18 11:33 UTC, kkthxbye-code reviewed
Seems to be missing both the delete and requeue actions. Especially the requeue action is useful for webhooks failing because of intermittent issues. The delete action can be useful in rare cases where a very large amout of webhooks were unnecessarily enqueued because of a bulk action or in rare cases where the Job object of a scheduled Job is deleted, but the backing task was not.

#14729 doesn't mention not porting that part of the UI. If not an oversight, this should be documented in both #14729 and the release notes.

2024-01-18 19:40 UTC, arthanson commented on netbox/core/tables/tasks.py
> +    id = tables.Column(empty_values=(), verbose_name=_("ID"))
yes, otherwise render doesn't get called

2024-01-19 14:27 UTC, jeremystretch requested changes

2024-01-19 14:27 UTC, jeremystretch commented on netbox/core/views.py
> +        return render(request, 'core/background_tasks.html', {
The template name should match the view name, e.g. `queue_list.html`.

2024-01-19 14:27 UTC, jeremystretch commented on netbox/core/views.py
> +class BackgroundQueuesListView(LoginRequiredMixin, View):
List views should use the singular form of the object name for consistency.
```suggestion
class BackgroundQueueListView(LoginRequiredMixin, View):
```

2024-01-19 14:27 UTC, jeremystretch commented on netbox/core/views.py
> +class BackgroundTasksListView(LoginRequiredMixin, View):
```suggestion
class BackgroundTaskListView(LoginRequiredMixin, View):
```

2024-01-19 14:27 UTC, jeremystretch commented on netbox/core/views.py
> +class BackgroundTaskDetailView(LoginRequiredMixin, View):
```suggestion
class BackgroundTaskView(LoginRequiredMixin, View):
```

2024-01-19 14:27 UTC, jeremystretch commented on netbox/core/tables/tasks.py
> +        return annotated_date(value)
Are these necessary? Elsewhere in the application we use `DateTimeColumn` without any custom rendering.

2024-01-19 14:27 UTC, jeremystretch commented on netbox/core/tables/tasks.py
> +        }
This is set on BaseTable.
```suggestion
```

2024-01-19 14:27 UTC, jeremystretch commented on netbox/core/tables/tasks.py
> +        }
```suggestion
```

2024-01-19 14:27 UTC, jeremystretch commented on netbox/core/tables/tasks.py
> +from ..models import Job
Remove unused imports.
```suggestion
from netbox.tables import BaseTable
from utilities.templatetags.helpers import annotated_date
```

2024-01-19 14:27 UTC, jeremystretch commented on netbox/core/tables/tasks.py
> +    status = tables.Column(empty_values=(), verbose_name=_("Status"))
This should render a colored badge similar to e.g. `status` on the Site model.

2024-01-19 14:27 UTC, jeremystretch commented on netbox/core/tables/tasks.py
> +        return record.get_status
I think we can avoid defining a custom render method by specifying an accessor on the column.

2024-01-19 14:27 UTC, jeremystretch commented on netbox/core/views.py
> +            raise Http404("Couldn't find job with this ID: %s" % job_id)
Error message needs to be wrapped with `gettext()`. Could also probably make it shorter, e.g. "Job {ID} not found."

2024-01-19 14:27 UTC, jeremystretch commented on netbox/core/views.py
> +            data_is_valid = False
Not sure what's going on here. Needs an explanatory comment.

2024-01-19 14:27 UTC, jeremystretch commented on netbox/core/views.py
> +        queue_index = int(queue_index)
`queue_index` is already passed as an integer by the URL path definition.
```suggestion
```

2024-01-30 14:51 UTC, jeremystretch commented
@arthanson could you please add tests for the new views? Happy to do a final pass once those are in place.

2024-01-30 23:18 UTC, arthanson commented
@jeremystretch tests added.

2024-01-31 22:01 UTC, jeremystretch approved these changes
@arthanson I took the liberty of doing some cleanup. There's a lot of opportunity to add more functionality, but IMO this meets the goal of #14729 and I'd rather not hold this up any longer. Please have a look at my changes from today; if you have no objections this is ready to be merged. Thanks!

2024-02-01 15:46 UTC, arthanson commented
@jeremystretch looks good to merge

2024-02-01 16:44 UTC, merged