15153 customize styling browseable rest api
netbox-community/netbox pull request #15474
Opened 2024-03-19 14:06 UTC by arthanson

### Fixes: #15153 

Limits on what can be changed without copying and modifying the base template into api.html, but made tweaks to bring it more in-line with app.  Just kept inline css as fairly minor changes needed and IMHO not worth tooling for separate css file.

![Monosnap Circuits | NetBox REST API 2024-03-19 07-03-39](https://github.com/netbox-community/netbox/assets/99642/713df0f8-4784-47ec-bdb4-6525d2b008a0)

2024-03-29 19:57 UTC, jeremystretch requested changes
It's a good start, but I see a few issues:

1. The navbar is not aligned properly
2. No visual contrast between the navbar and page content
3. Too much white space

![rest_web_ui](https://github.com/netbox-community/netbox/assets/13487278/dcde8884-b764-4a96-8bbc-65cea037126b)

2024-03-29 19:57 UTC, jeremystretch commented on netbox/templates/rest_framework/api.html
> +  <style>
We shouldn't have inline CSS anywhere. Any custom styles should be defined as SASS under `project-static/styles/` along with the native stylesheets. We can build and package a custom CSS just for the REST web UI.

2024-04-01 16:36 UTC, arthanson commented
Changed to dark header and adjusted spacing / alignment of items

2024-05-17 16:37 UTC, jeremystretch commented
We're going to punt on this one for now and revisit once we've spent more time improving the overall UI design.

2024-05-17 16:37 UTC, closed without merging