Fixes: #14567 - Export current view of IP Addresses
netbox-community/netbox pull request #15659
Opened 2024-04-08 12:42 UTC by Julio-Oliveira-Encora

### Fixes: #14567 

It added a script in "table_controls_htmx.html" to add the parameters to the URL (changing the htmx behavior).

Another script was created in "export.html" to append the parameters to the HREF to export the current view. 

It was tested exporting devices, IP Address, and IP Range, with and without a quick search.

2024-04-15 16:21 UTC, jeremystretch requested changes

2024-04-15 16:21 UTC, jeremystretch commented on netbox/templates/inc/table_controls_htmx.html
> +</script>
All scripting should be written in TypeScript and should live in a module under `project-static/src/` with the rest of the frontend scripting.

2024-04-22 13:05 UTC, jeremystretch requested changes
Getting closer!

2024-04-22 13:05 UTC, jeremystretch commented on netbox/project-static/src/search.ts
> +    const linkUpdated = link?.href + '&' + search_parameter;
This appears to append successive queries, e.g. `?q=foo&q=bar`. Any previous query should be replaced by the new one.

2024-04-22 15:27 UTC, Julio-Oliveira-Encora commented on netbox/project-static/src/search.ts
> +    quicksearch.addEventListener('change', handleQuickSearchParams);
I created a function to clear the query parameters and used it in the "quickSearchEventHandler"; this way, when the Quick Search field is cleaned up, the parameters are also removed.

The same function is used when the search is changed, cleaning the current parameters before adding the new ones.

2024-05-20 13:42 UTC, jeremystretch requested changes

2024-05-20 13:42 UTC, jeremystretch commented on netbox/project-static/src/search.ts
> +      );
Please revert any changes that aren't pertinent to the new functionality to limit the scope of PR reviews. (If cleanup is needed, we can tackle those items in a separate housekeeping issue.)

2024-05-20 13:42 UTC, jeremystretch commented on netbox/project-static/src/search.ts
> +
```suggestion
```

2024-05-20 13:42 UTC, jeremystretch commented on netbox/project-static/src/search.ts
> +  const link = document.getElementById("current_view") as HTMLLinkElement;
Could we give this element a slightly more descriptive name, to help prevent confusion?
```suggestion
  const link = document.getElementById("export_current_view") as HTMLLinkElement;
```

2024-05-29 14:00 UTC, jeremystretch requested changes

2024-05-29 14:00 UTC, jeremystretch commented on netbox/project-static/src/search.ts
> +    quicksearch.addEventListener('change', handleQuickSearchParams);
This does not appear to be working. After entering a search term in the quicksearch field and clicking the clear button, the term is still attached to the export link.

2024-05-30 19:43 UTC, arthanson requested changes
I'm still getting the whole table when I'm exporting.  See screenshot, I only have one Address that is in the table, but export I get all.
![Monosnap IP Addresses | NetBox 2024-05-30 12-42-52](https://github.com/netbox-community/netbox/assets/99642/936bfad6-b14f-445f-9c00-e773782a2082)

2024-06-03 14:07 UTC, Julio-Oliveira-Encora commented
I tested it. When I exported, I got only one IP address.

![ip_addr](https://github.com/netbox-community/netbox/assets/149191228/3f758f7c-3e9c-412b-aa57-c08329deb9f1)
![export_IP_addr](https://github.com/netbox-community/netbox/assets/149191228/d1a37038-c27f-40f7-9d3e-c25c6cfe1fa3)

2024-06-04 18:57 UTC, Julio-Oliveira-Encora commented
I checked out to another branch and exported the current view. Then, I went back to the branch that fixed the export current view. Refreshing the page was necessary for it to work correctly.

2024-06-06 13:35 UTC, jeremystretch approved these changes
Thanks @Julio-Oliveira-Encora!

2024-06-06 13:35 UTC, merged