Fixes #15717 - Unable to assign a VM in Site to Cluster without Site
netbox-community/netbox pull request #15763
Opened 2024-04-18 15:30 UTC by nopg

### Fixes: #15717 

Adds to existing IF statement for VirtualMachine.clean()  (to match existing check for Device.clean()) to allow for VM to be assigned to a Cluster without a Site. 

Updated existing VM test to check for this new use case, and added Device tests for Clusters with Sites matching/not matching as well.

2024-05-22 19:34 UTC, arthanson commented
@nopg can you please fix the merge conflicts

2024-05-30 19:07 UTC, arthanson requested changes
@nopg I tried this PR - 

I go to edit a VM that has a site assigned and I can't get the unassigned cluster in the dropdown (see screenshot below) I have created a 'tcluster' that doesn't appear in the selection.  I think the queryset for the dropdown needs to be updated. 
![Monosnap Editing virtual machine child vm | NetBox 2024-05-30 12-04-54](https://github.com/netbox-community/netbox/assets/99642/ba920cc3-a67f-457a-816f-f979e765b2ab)

Note: without the PR I can assign a cluster (not assigned to a site) to a device that is assigned to a device fine, so I think this only applies to VM.

2024-05-31 16:55 UTC, nopg commented
I swear i checked that myself and it was working (at least back on 3.x)! But yes I see that issue as well. I've got a lot going on the next few days but plan on updating this as soon as I can, just wanted to reply here first.

2024-06-04 17:20 UTC, nopg commented
Ok, done. As you mentioned this doesn't apply to Devices just VM's. I removed the query_params from VM's/Cluster, which is how it looks on the Device side as well.

2024-06-07 15:40 UTC, arthanson commented
@nopg The dropdown works now but there is a validation error if you try to save
![Monosnap Editing virtual machine vm9 | NetBox 2024-06-07 08-37-46](https://github.com/netbox-community/netbox/assets/99642/d129c795-89e3-4b48-89a3-e0c5859d7708)

2024-06-07 17:43 UTC, nopg commented
@arthanson I can't reproduce that...I can save or create a VM-with-site into my Cluster without a site now, screenshot below. The validation should have been part of the initial change I made to virtualmachine.py in this PR.

![vms](https://github.com/netbox-community/netbox/assets/24619595/879c4200-b095-4dd0-967a-0bf64a7d9823)

2024-06-11 18:25 UTC, arthanson commented
@nopg I see the issue, I actually had TC assigned to a different site, the problem is that the dropdown is now displaying Clusters in all sites so you can select an invalid cluster and get the error message above.  I have 3 clusters to test: TC is unassigned, TC2 is a different site then the VM and TC3 is the same site.  Only TC and TC3 should be showing in the dropdown (see screenshot). 
![Monosnap Editing virtual machine vm9 | NetBox 2024-06-11 11-21-45](https://github.com/netbox-community/netbox/assets/99642/0050fd8e-7454-4dc4-a4f2-3d69d22eeca5)

2024-06-12 05:02 UTC, nopg commented
Ok @arthanson, sounds good. I had initially noticed the behavior you are describing, but saw that this same behavior also already existed with Devices, so decided to just 'match' the Devices behavior and leave it be.

After looking into it though, I was able to produce the desired behavior (showing only same-site Clusters in the list, or Clusters not attached to any Site) with query_params, so I also updated the associated cluster query_params for Device as well as VirtualMachine. I assume at this point it's ok to include that in this PR. We are hopefully good to go at this point.

2024-06-20 14:45 UTC, jeremystretch approved these changes
Thanks @nopg!

2024-06-20 14:59 UTC, merged