15815 convert dashboard widgets for users/groups
netbox-community/netbox pull request #15839
Opened 2024-04-24 20:42 UTC by arthanson

### Fixes: #15815 

Convert dashboard widgets using `users.netboxuser` -> `users.user` and `users.netboxgroup` -> `users.group`

2024-04-25 13:13 UTC, jeremystretch requested changes
It feels like we should also take this opportunity to improve error handling in `extras.dashboard.widgets.get_models_from_content_types()`. IMO it's reasonably to fail silently when attempting to resolve a content type that doesn't exist.

2024-04-25 13:13 UTC, jeremystretch commented on netbox/extras/migrations/0115_convert_dashboard_widgets.py
> +            breakpoint()
```suggestion
```

2024-04-25 13:13 UTC, jeremystretch commented on netbox/extras/migrations/0115_convert_dashboard_widgets.py
> +                models = widget['config']['models']
```suggestion
            if models := widget['config'].get('models'):
```

2024-04-26 20:09 UTC, arthanson commented on netbox/extras/migrations/0115_convert_dashboard_widgets.py
> +            breakpoint()
doh!

2024-05-01 13:56 UTC, jeremystretch approved these changes
Thanks @arthanson!

2024-05-01 13:56 UTC, merged