15802 change table anchor color
netbox-community/netbox pull request #15841
Opened 2024-04-24 22:05 UTC by arthanson

### Fixes: #15802 

This is what tabler has in their demo (they have a class on the table items, which we wouldn't want to do for each one. However it doesn't have any contrast between a link and a non-link (see screenshot) not sure if we want this or to go with a different tabler link color...

![Monosnap Sites | NetBox 2024-04-24 15-03-07](https://github.com/netbox-community/netbox/assets/99642/e33b6b07-180f-47bc-a5aa-e9eb5d4412fe)

2024-04-25 12:28 UTC, jeremystretch requested changes
> However it doesn't have any contrast between a link and a non-link (see screenshot) not sure if we want this or to go with a different tabler link color...

We definitely still want to render links in a different color. #15802 is just to increase the contrast of links under dark mode.

2024-05-01 14:00 UTC, jeremystretch requested changes
The color change should only apply to dark mode.

![screenshot](https://github.com/netbox-community/netbox/assets/13487278/081cb4db-0bca-4aec-9fee-3f1f7e1e77eb)

2024-05-01 19:56 UTC, arthanson commented
I tried using different media queries but they didn't work properly when switching between light and dark, even specifically defining media queries for both.  As a compromise I picked a filter to slightly lighten the link which seems to look fairly good in both light and dark.

2024-05-02 17:06 UTC, jeremystretch requested changes

2024-05-02 17:06 UTC, jeremystretch commented on netbox/project-static/styles/overrides/_tabler.scss
> +  filter: brightness(110%);
Please add a comment explaining why the rule exists.

2024-05-02 20:03 UTC, jeremystretch approved these changes

2024-05-02 20:06 UTC, merged