Feature 15348 - Quick Access Saved Filters
netbox-community/netbox pull request #15862
Opened 2024-04-26 15:20 UTC by Julio-Oliveira-Encora

### Feature: #15348

A dropdown was added to list and apply the saved filters to the current view.

2024-05-20 13:13 UTC, jeremystretch requested changes
Although functional, displaying the active saved filters in both the original tag form and in the selector widget may be confusing to the user. IMO we should display applied filters only in the selector widget, and show only individual filter values as removable colored tags.

![screenshot](https://github.com/netbox-community/netbox/assets/13487278/28f2b49c-7adc-44e7-ac04-19ce2bbcb554)

2024-05-20 13:13 UTC, jeremystretch commented on netbox/templates/inc/table_controls_htmx.html
> +      <input type="search" results="5" name="q" id="quicksearch" class="form-control px-2 py-1"
We need to figure out how to make the new dropdown visually consistent with the quick search box.

![screenshot](https://github.com/netbox-community/netbox/assets/13487278/bfe78acb-f17f-4f6c-ac88-3faeafafdbb4)

2024-05-20 13:13 UTC, jeremystretch commented on netbox/project-static/src/savedFiltersSelect.ts
> +  let preFilter = "?";
```suggestion
  const preFilter = '?';
```

2024-05-20 13:13 UTC, jeremystretch commented on netbox/project-static/src/savedFiltersSelect.ts
> +import {isTruthy} from "./util";
This and some other lines within the file trigger complaints from `prettier`.

```suggestion
import { isTruthy } from './util';
```

2024-05-20 13:13 UTC, jeremystretch commented on netbox/project-static/src/savedFiltersSelect.ts
We should probably move this under `forms/`.

2024-05-23 16:20 UTC, arthanson commented
@Julio-Oliveira-Encora here are the changes after discussion on this:

* Remove the blue chits for the saved filters only, so normal filters will still show there (The functionality for saving your filters and such should remain).  So the selected saved filters will only show in the save filters dropdown.
* We don't need to change the saved filters to use a placeholder, having the label there is fine.
* Make the vertical height of the dropdown match the Quick Search so at start they aren't different sizes.  You can adjust the text height and padding of the Saved filters, you may also need to tweak the quick search if needed.  Note: If you select many saved filters it will wrap and grow the select box, this is fine - we just care about the initial page look when you have no filters (or one filter) selected.

2024-05-27 18:23 UTC, Julio-Oliveira-Encora commented
@arthanson I changed the CSS for quick search, because I did get to change the CSS for Dropdown. Please, check them.

2024-05-28 16:23 UTC, arthanson requested changes
@Julio-Oliveira-Encora I added a saved filter and then selected it, however it didn't actually filter the table - see screenshots.  The first is the filter applied manually, the second is selecting it from the saved filter list, they number of results should match but don't.
![Monosnap IP Addresses | NetBox 2024-05-28 09-19-39](https://github.com/netbox-community/netbox/assets/99642/cee061f9-03cc-4444-b5ae-d1c53099016d)
![Monosnap IP Addresses | NetBox 2024-05-28 09-20-03](https://github.com/netbox-community/netbox/assets/99642/5acf95fa-37a7-4e16-9b4a-2ec1181e4ba7)

2024-05-31 16:22 UTC, arthanson commented
@Julio-Oliveira-Encora I just re-tested this, it is happening when I don't have HTMX navigation enabled

2024-06-03 15:19 UTC, Julio-Oliveira-Encora commented
I tested with HTMX Navigation disabled:

![Preferences](https://github.com/netbox-community/netbox/assets/149191228/7dcb1a5a-4b57-45ce-8473-3f568317a027)


For IP Address I created a "Saved Filter" for IPV4 and Active. It worked:

![ip_saved_filter](https://github.com/netbox-community/netbox/assets/149191228/40b7bad1-b5fc-4488-971f-3f7af46bf09d)
![ip_filters](https://github.com/netbox-community/netbox/assets/149191228/128e6abe-9cf1-4127-9413-1875e76619c6)


For sites I tested too:

![sites](https://github.com/netbox-community/netbox/assets/149191228/e41fcb30-f36b-4bf9-a45c-e55787b67c92)
![Screenshot from 2024-06-03 12-17-17](https://github.com/netbox-community/netbox/assets/149191228/f444069e-3ff7-40aa-aac9-9e0ec31f0e9f)

2024-06-07 16:41 UTC, arthanson commented
@Julio-Oliveira-Encora almost there - can you remove the saved-filters from the filters tab. With both the dropdown and it being in filters tab you can get the UI showing both which isn't great:
![Monosnap Devices | NetBox 2024-06-07 08-47-39](https://github.com/netbox-community/netbox/assets/99642/93b054c5-108d-464c-b2ef-6144bc68f15c)

2024-06-07 17:48 UTC, arthanson commented on netbox/templates/inc/table_controls_htmx.html
> +    <label class="my-2" for="id_filter_id">Saved Filter</label>
Also put {% trans around this

2024-06-10 14:42 UTC, jeremystretch requested changes

2024-06-10 14:42 UTC, jeremystretch commented on netbox/project-static/src/appliedFilter.ts
> +        appliedFilter.hidden = true;
We should not rely on Javascript to hide this element; rather it should simply not be rendered in the template.

@arthanson can you help Julio with this please?

2024-06-11 15:50 UTC, arthanson commented
@Julio-Oliveira-Encora if you need any help with hiding the column in the table, please let me know.

2024-06-11 17:28 UTC, Julio-Oliveira-Encora commented
@arthanson  and @jeremystretch  
Could the function `applied_filters` be modified to check if the form only contains the  `filter_id` and return an empty `applied_filters` to avoid using Javascript?

2024-06-18 14:03 UTC, jeremystretch approved these changes
I've omitted saved filters from the "applied filters" list and did some cosmetic cleanup of the selector widget.

2024-06-18 15:26 UTC, Julio-Oliveira-Encora commented
@jeremystretch Should I make some additional changes to it?

2024-06-18 15:53 UTC, arthanson approved these changes

2024-06-18 15:58 UTC, merged