Adds extra column for result on the script job table
netbox-community/netbox pull request #16065
Opened 2024-05-09 17:34 UTC by abhi1693

### Fixes: #15983

2024-05-09 18:24 UTC, jeremystretch requested changes
Thanks @abhi1693! Just a couple minor nits.

2024-05-09 18:24 UTC, jeremystretch commented on netbox/extras/views.py
> +                    template_code='<a href="{% url "extras:script_result" job_pk=record.pk %}">{{ record.completed }}</a>'
We've started presenting all dates & times in ISO 8601 format now using the `isoformat()` template filter for consistency.

![screenshot](https://github.com/netbox-community/netbox/assets/13487278/f53e18a8-a8de-4752-941f-963ad8dbc766)

2024-05-09 18:24 UTC, jeremystretch commented on netbox/extras/views.py
> +                    template_code='<a href="{% url "extras:script_result" job_pk=record.pk %}">{{ record.completed }}</a>'
We also need to explicitly pass the verbose name for each column now to support translation (e.g. `verbose_name=_('Result')`).

2024-05-09 19:41 UTC, bitcollector1 commented
much appreciated folks!

2024-05-09 20:28 UTC, bitcollector1 commented
This is much appreciated. Is there anyway to get the results from the main job page? the one with ALL the jobs? 

I use this page the most often. took me awhile to figure out why the results were not posting here:
https://netdevbox.hwe.ebay.com/core/jobs/

but I do see the results now listed here:
https://netdevbox.hwe.ebay.com/extras/scripts/17/jobs/

2024-05-09 21:30 UTC, bitcollector1 commented
can we add this same info to the core jobs table?  That is the page I use the most to check the status of all my various jobs.

2024-05-10 04:57 UTC, abhi1693 commented
> can we add this same info to the core jobs table

It's out of scope. Results column only makes sense for scripts and jobs table can have other types in it

2024-05-14 11:56 UTC, jeremystretch commented
Rather than adding another column to the table, it might make more sense to override the "completed" column so that it links to the script result. We could do this in a generic way so that the "completed" column in any jobs table links to the relevant record where applicable.

2024-05-14 16:12 UTC, bitcollector1 commented
> Rather than adding another column to the table, it might make more sense to override the "completed" column so that it links to the script result. We could do this in a generic way so that the "completed" column in any jobs table links to the relevant record where applicable.


Thanks Jeremy, 

All I'm looking for us parity with 3.7, where you can get to the results from the main page. Appreciate the support and excellent work on a great product.

2024-05-30 14:37 UTC, arthanson commented
@abhi1693 Are you looking at overriding the completed column as Jeremy mentioned or do you think this is good to go as is?

2024-06-14 13:35 UTC, jeremystretch commented
Closing this for inactivity.

2024-06-14 13:35 UTC, closed without merging