add USE_I18N setting to optionally turn translation off
netbox-community/netbox pull request #16096
Opened 2024-05-12 08:56 UTC by amyasnikov

### Fixes: #16055

2024-05-13 13:41 UTC, jeremystretch requested changes
While this implements the root translation control, it does not address UX: A user can still change his or her language, and would naturally assume that preference to have an effect. Please extend the PR to also disable the user's language preference when translation has been disabled (or at a minimum indicate as much to the user).

2024-05-13 13:41 UTC, jeremystretch commented on netbox/netbox/settings.py
> +USE_I18N = getattr(configuration, 'USE_I18N', True)
While an argument can be made for preserving Django setting names, I expect the term i18n won't make sense to most users. IMO we should call this something like `ENABLE_TRANSLATION`.

2024-05-13 23:45 UTC, amyasnikov commented
@jeremystretch fixed, pls take a look

2024-05-14 13:10 UTC, jeremystretch approved these changes
Thanks @amyasnikov!

2024-05-14 13:21 UTC, merged