16149 add (optional) obj hyperlink to script list table
netbox-community/netbox pull request #16271
Opened 2024-05-23 20:14 UTC by arthanson

### Fixes: #16149

2024-06-06 12:41 UTC, jeremystretch requested changes
This does not appear to resolve #16149; I see the same output in the script result before and after the change. Additionally, the table configuration button does not work on the script result view.

2024-06-10 18:27 UTC, arthanson commented
> This does not appear to resolve #16149; I see the same output in the script result before and after the change. Additionally, the table configuration button does not work on the script result view.

@jeremystretch I'm not seeing those issues?  With the branch I get the configuration button, which you need to do as the object is an optional parameter.  If you do add the parameter then you do get a clickable link (second screenshot).  Is there a data condition I'm missing that is causing the config screen not to appear on yours?

![Monosnap NewBranchScript | NetBox 2024-06-10 11-24-25](https://github.com/netbox-community/netbox/assets/99642/e5bad0a9-3d03-4c4e-8167-4f07c5197e3d)
![Monosnap NewBranchScript | NetBox 2024-06-10 11-24-40](https://github.com/netbox-community/netbox/assets/99642/3784ca85-1a98-4cf1-b853-f5f3367acab2)

2024-06-11 12:40 UTC, jeremystretch commented
@arthanson looks like the table configuration button is left in a broken state when the script first completes. It's functional on successive reloads. The modal content is likely missing on the first load.

2024-06-11 12:42 UTC, jeremystretch requested changes
Table configuration button is broken on completion of script execution. Also, we should probably make `object` a default table column.

2024-06-11 20:00 UTC, arthanson commented
Made object default, the table configuration button wasn't working as the filter list is only included when the script finishes, so made the button dependent on that as well.

2024-06-12 13:34 UTC, jeremystretch requested changes

2024-06-12 13:34 UTC, jeremystretch commented on netbox/extras/scripts.py
> +                self.logger.log(LogLevelChoices.SYSTEM_LEVELS[level], message)
This appears to be redundant to the line above (which is already prefixing the message with `{obj}: `).

2024-06-12 13:34 UTC, jeremystretch commented on netbox/extras/tables/tables.py
> +    )
I would ditch the URL column. IMO it's poor form to print a raw URL as a value, and it's redundant to the `object` column.

2024-06-21 14:04 UTC, jeremystretch approved these changes
Thanks @arthanson!

2024-06-21 14:04 UTC, merged