Fixes: #16083 - Add font-variant-ligatures setting to disable ligatur…
netbox-community/netbox pull request #16383
Opened 2024-06-03 02:10 UTC by DanSheps

### Fixes: #16083 - Add font-variant-ligatures setting to disable ligatures on chromium

* Add font-variant-ligatures setting and set to none in _tabler.scss overrides file.
* Bundle styles

2024-06-03 14:29 UTC, jeremystretch requested changes

2024-06-03 14:45 UTC, DanSheps commented on netbox/project-static/styles/overrides/_tabler.scss
> +body {
Fixed it up, sorry about that

2024-06-03 15:42 UTC, jeremystretch commented
Seems like it's still happening inside input fields. @DanSheps could you take a look? Seems fine when rendered as static text on the page. (This is on Firefox btw.)

![screenshot](https://github.com/netbox-community/netbox/assets/13487278/edba2ff8-b6d6-43f3-a18b-7ae6c13670e4)

2024-06-03 18:09 UTC, DanSheps commented
> Seems like it's still happening inside input fields. @DanSheps could you take a look? Seems fine when rendered as static text on the page. (This is on Firefox btw.)

Looks like chrome has a specific override for `<input>` within the browser CSS.  Likely the same in Firefox.  I added `<input>` to the override file

2024-06-04 13:02 UTC, jeremystretch commented
There are other elements (e.g. `<textarea>`) where this also needs to be applied, so I simplified it to a global rule.

2024-06-04 13:02 UTC, jeremystretch approved these changes
Thanks @DanSheps!

2024-06-04 13:02 UTC, merged