16307 - Restore ability for reports to be able to log_success without generating a message
netbox-community/netbox pull request #16403
Opened 2024-06-04 14:16 UTC by Julio-Oliveira-Encora

### Fixes: #16307

It was added to bypass the log message when the status is success, and the message is None.

It was tested using `log_success(None, None)`,  `log_success("", None)`, and `log_sucess()`.

2024-06-04 15:50 UTC, arthanson requested changes

2024-06-04 15:50 UTC, arthanson commented on netbox/extras/signals.py
> +    """Fires when an object is deleted."""
Can you remove this from the PR?  Nothing to do with the chagne.

2024-06-04 15:50 UTC, arthanson commented on netbox/extras/views.py
> +                    print(log)
Remove this print statement

2024-06-07 15:13 UTC, arthanson commented
@Julio-Oliveira-Encora it looks like log_success() works now with this change, can you please add a note to the documentation on scripts about this.

2024-06-10 15:34 UTC, arthanson approved these changes

2024-06-11 12:54 UTC, jeremystretch requested changes
@Julio-Oliveira-Encora have you tested this before submitting the PR? You haven't actually updated [the method's signature](https://github.com/netbox-community/netbox/blob/eb3d4230778f26fa5be38c7d6b3e1205f905fc93/netbox/extras/scripts.py#L513) to make `message` an optional argument. When calling `log_success()` in a script, an exception is raised:

```
Traceback (most recent call last):
  File "/home/jstretch/projects/netbox/netbox/extras/scripts.py", line 658, in _run_script
    script.output = script.run(data, commit)
  File "/home/jstretch/projects/netbox/netbox/scripts/test2.py", line 19, in run
    self.log_success()
TypeError: BaseScript.log_success() missing 1 required positional argument: 'message'
```

2024-06-11 13:07 UTC, Julio-Oliveira-Encora commented
I tested it before submitting the PR. I will check the method's signature and test again.

2024-06-12 12:52 UTC, jeremystretch requested changes
I'm unclear on what the intended goal is here. As it stands, calling `log_success(obj=thing)` in a custom script does not generate any output. This seems completely pointless, and confusing.

#16307 seems limited to incrementing success counters in _reports_ only; if that's the case, the `log_*()` methods on the Report class should be modified to call `self._log()` directly rather than proxying through the `log_*()` methods on Script, to avoid changing them.

2024-06-13 18:09 UTC, Julio-Oliveira-Encora commented
@jeremystretch About the log methods on the Report class, should I change them this way?
   ```
 def log_success(self, obj=None, message=None):
        self._log(message, obj, level=LogLevelChoices.LOG_SUCCESS)
```
Or follow the argument positional from scripts, where `message` is before `obj`?
   ```
 def log_success(self, message, obj=None):
        self._log(message, obj, level=LogLevelChoices.LOG_SUCCESS)
```

2024-06-13 18:24 UTC, Julio-Oliveira-Encora commented
We could discuss it more because the user is asking for the change for Reports, but maybe he wants to use it in all types of scripts.

2024-06-24 13:43 UTC, closed without merging

2024-06-24 13:43 UTC, jeremystretch commented
@Julio-Oliveira-Encora I think we went down the wrong path with this a bit. I've submitted an alternate PR (#16697) which I believe addresses the proposal in #16307.