16256 - Allow alphabetical ordering of bookmarks on dashboard
netbox-community/netbox pull request #16426
Opened 2024-06-06 13:38 UTC by Julio-Oliveira-Encora

### Fixes: #16256

Added alphabetical ordering option for bookmarks.

2024-06-07 15:44 UTC, arthanson approved these changes

2024-06-10 14:04 UTC, jeremystretch requested changes

2024-06-10 14:04 UTC, jeremystretch commented on netbox/extras/dashboard/widgets.py
> +                bookmarks = sorted(Bookmark.objects.filter(user=request.user),
We should define the base queryset (`Bookmark.objects.filter(user=request.user)`) once, and then effect ordering one way or the other depending on the selected option. This ensures that any future modifications to the base queryset are needed only once.

2024-06-10 14:04 UTC, jeremystretch commented on netbox/extras/choices.py
> +        (ORDERING_NAME_AZ, _('Name (A-Z)')),
This ordering isn't technically by name, as not all model have a `name` attribute (circuits, for instance). Let's change this to "alphabetical" to be more accurate.

2024-06-10 14:04 UTC, jeremystretch commented on netbox/extras/choices.py
> +        (ORDERING_NAME_AZ, _('Name (A-Z)')),
I'm not sure how useful it would be, but it feels like we should add an option for reverse alphabetical ordering as well for completeness.

2024-06-11 13:02 UTC, jeremystretch approved these changes
Thanks @Julio-Oliveira-Encora!

2024-06-11 13:21 UTC, merged