Fixes #1655. Removed explicit field references.
netbox-community/netbox pull request #1656
Opened 2017-10-27 18:27 UTC by Ichabond

### Fixes:
Fixes #1655

Further field name references were found in `consoleport.html`. These have now been removed, so we rely on proper a proper `__str__` implementation of both `ConsolePort` and `ConsoleServerPort`.

2017-10-30 20:01 UTC, jeremystretch requested changes
Most of these are fine, but there are several instances where `name` is referenced intentionally.

2017-10-30 20:01 UTC, jeremystretch commented on netbox/templates/secrets/inc/secret_tr.html
> -    <td>{{ secret.name }}</td>
We specifically want to only show the name here (this is a column in a table).

2017-10-30 20:01 UTC, jeremystretch commented on netbox/secrets/models.py
> +        if self.role and self.device and self.name:
We still want to return the role and device if no name is set.

2017-10-30 20:01 UTC, jeremystretch commented on netbox/templates/dcim/inc/rack_elevation.html
> +                            {{ u.device|default:u.device.device_role }}
We want to look specifically at `name` in this case, because `__str__` calls `display_name()`, which will return the device type if no name is set.

2017-10-30 20:01 UTC, jeremystretch commented on netbox/templates/dcim/inc/rack_elevation.html
> -                        <span>{{ u.device.name|default:u.device.device_role }}</span>
Same as above.

2017-10-30 20:01 UTC, jeremystretch commented on netbox/templates/dcim/rack_elevation_list.html
> -                            <strong><a href="{% url 'dcim:rack' pk=rack.pk %}">{{ rack.name|truncatechars:"25" }}</a></strong>
As with devices, we intentionally reference `name` here to avoid calling `display_name()`.

2017-10-30 20:01 UTC, jeremystretch commented on netbox/templates/dcim/rack_elevation_list.html
> -                            <strong><a href="{% url 'dcim:rack' pk=rack.pk %}">{{ rack.name|truncatechars:"25" }}</a></strong>
Same as above.

2017-10-30 20:01 UTC, jeremystretch commented on netbox/templates/ipam/inc/service.html
> -    <td>{{ service.name }}</td>
We want only the service name here.

2017-10-31 17:29 UTC, Ichabond commented
I've gone over them, and I agree. I've pushed a new commit reverting those changes explicitly mentioned. Thanks for the feedback on this.

2017-11-02 15:46 UTC, jeremystretch commented
LGTM

2017-11-02 15:46 UTC, jeremystretch approved these changes

2017-11-02 15:51 UTC, merged