Fixes #11371 adds an 100Base SFP interface
netbox-community/netbox pull request #16809
Opened 2024-07-03 13:12 UTC by RobertH1993

### Fixes: #11371 

Adds the requested SFP type

2024-07-03 13:13 UTC, RobertH1993 commented
Comment so maintainer is able to assign.

2024-07-08 13:50 UTC, jeremystretch requested changes

2024-07-08 13:50 UTC, jeremystretch commented on netbox/dcim/choices.py
> +    TYPE_100ME_FX_SFP = '100base-fx-sfp'
```suggestion
    TYPE_100ME_SFP = '100base-x-sfp'
```

2024-07-08 13:50 UTC, jeremystretch commented on netbox/dcim/choices.py
> +
Remove errant newline.
```suggestion
```

2024-07-08 13:50 UTC, jeremystretch commented on netbox/dcim/choices.py
> +                (TYPE_100ME_FX_SFP, '100BASE-FX-SFP (10/100ME FIBER)'),
The SFP interface type does not imply a specific medium (e.g. FX), just the line rate. Also, this needs to be moved to the "Ethernet (modular)" group as it is modular in nature.
```suggestion
                (TYPE_100ME_SFP, 'SFP (100ME)'),
```

2024-08-08 04:04 UTC, closed without merging