16650 button contrast issues
netbox-community/netbox pull request #16845
Opened 2024-07-08 18:14 UTC by andrewgormley

### Fixes: #16650

- [x]  (List page) Low contrast on buttons [both, multiple]
- [x]  (Racks) Low contrast download svg button [dark, multiple]
- [x]  (Buttons) Focus state on buttons is missing focus ring causing contrast and CVD issue [both, global]
- [x]  (Misc) Low contrast on cancel button [dark, multiple]
- [x]  (Misc) Low contrast on create combo button [dark, multiple]

2024-07-09 04:54 UTC, arthanson commented
@andrewgormley just thought I'd mention - I actually find the black text on some of the buttons much harder to read, for example the export button with black on fuscia (see screenshot) sort of strains/hurts my eyes.  Also the delete button (black on red) isn't as bad but still seems less readable than before.  Not sure if it's just my eyes.

<img width="1410" alt="Devices | NetBox 2024-07-09 11-42-23" src="https://github.com/netbox-community/netbox/assets/99642/f8c8c5bb-4008-4fbc-b198-a90349ae8fd7">
<img width="1419" alt="Devices | NetBox 2024-07-09 11-43-47" src="https://github.com/netbox-community/netbox/assets/99642/131883d1-e613-4b43-8727-c27501b6a93f">
<img width="570" alt="PP:B117 | NetBox 2024-07-09 11-44-46" src="https://github.com/netbox-community/netbox/assets/99642/bff99183-cc08-4dda-ad49-0da766682ff9">

2024-07-09 13:10 UTC, jsenecal commented
I'm sorry if I come late to this discussion, but wouldn't it be best to address some of these color scheme issues as a user preference `Use high-contrast colors and buttons` ? 

This black on [green,orange,yellow,blue,purple] looks very harsh for the non-color impaired IMHO.

2024-07-10 14:38 UTC, jeremystretch requested changes

2024-07-10 14:38 UTC, jeremystretch commented on netbox/project-static/styles/overrides/_tabler.scss
> +      }
Why is this needed?

2024-07-10 14:38 UTC, jeremystretch commented on netbox/project-static/styles/overrides/_tabler.scss
> +}
This doesn't seem to have any effect? A button with `btn-outline-secondary` appears to render the same whether or not this rule is in place AFAICT.

2024-07-10 14:39 UTC, jeremystretch commented
I realize this is subjective, but I'm not a fan of the brighter colors. As other have noted, it makes the text more difficult to read IMO.

Original:
![screenshot1](https://github.com/netbox-community/netbox/assets/13487278/56c0667a-4a0e-46bf-9316-61162fcc5b66)

Modified:
![screenshot2](https://github.com/netbox-community/netbox/assets/13487278/5a94cc26-c956-4342-a419-637aacd3efd0)

2024-07-16 18:24 UTC, jeremystretch approved these changes

2024-07-16 18:26 UTC, jeremystretch commented
I've attached the [reverted changes](https://github.com/user-attachments/files/16255067/pr16845_reverted.txt) for future reference.

2024-07-16 18:29 UTC, merged