DRAFT: 7025 circuit redundancy
netbox-community/netbox pull request #16945
Opened 2024-07-19 10:29 UTC by arthanson

### Fixes: #7025

2024-07-22 17:02 UTC, jeremystretch requested changes
Some other notes:

- The CircuitGroup view should include a "circuits" tab to easily list assigned circuits.

- There should be some convenient path to assign a circuit to a group from the circuit view.

- Looks like we're missing a [search index](https://netbox.readthedocs.io/en/stable/development/adding-models/#9-create-a-searchindex-subclass) for CircuitGroup.

2024-07-22 17:02 UTC, jeremystretch commented on netbox/templates/circuits/circuitgroupassignment.html
> +      {% include 'inc/panels/related_objects.html' %}
This panel is not needed.

2024-07-22 17:02 UTC, jeremystretch commented on netbox/templates/circuits/circuitgroupassignment.html
> +      {% include 'inc/panels/related_objects.html' %}
Missing the custom fields panel.

2024-07-23 09:15 UTC, arthanson commented on netbox/circuits/models/circuits.py
> +    circuit = models.ForeignKey(
I looked at it but it is never used anywhere and adds complexity to the related_counts.

2024-07-23 09:37 UTC, arthanson commented on netbox/circuits/models/circuits.py
> +    circuit = models.ForeignKey(
RE "The CircuitGroup view should include a "circuits" tab to easily list assigned circuits.

There should be some convenient path to assign a circuit to a group from the circuit view.
"
For the detail view the "Related Objects" I thought took the place of that, that is the way all the other group ones do it from what I can see. 

Also, I don't see a paradigm for the other group objects having an assignment on the object page (Tunnel Group, Tenant Group)?  Do we have a UI pattern for this somewhere?

2024-07-24 14:36 UTC, jeremystretch commented on netbox/templates/circuits/circuitgroupassignment.html
> +      {% include 'inc/panels/related_objects.html' %}
Disregard; we'll keep this in place instead of adding a separate tab view.

2024-07-24 16:24 UTC, merged