Fixes: #17320 - New screenshots for 4.1 UI
netbox-community/netbox pull request #17331
Opened 2024-08-30 22:25 UTC by bctiemann

### Fixes: #17320

New screenshots for the 4.1 UI/colors. Also normalizes all the screenshots to the same width.

2024-08-30 22:36 UTC, bctiemann commented
This should probably be squashed.

2024-09-02 13:11 UTC, jeremystretch requested changes

2024-09-02 13:11 UTC, jeremystretch commented on docs/media/screenshots/cable-trace.png
This is much taller than the original. It can be cropped to stop at the bottom of the trace diagram.

2024-09-02 13:11 UTC, jeremystretch commented on docs/media/screenshots/home-dark.png
The side navigation bar doesn't appear to render correctly in these screenshots. It doesn't extend to the bottom of the page.

2024-09-02 13:13 UTC, bctiemann commented on docs/media/screenshots/home-dark.png
Hmm, yeah -- I was using the built-in Chrome screenshot tool, I might have to do it manually in Photoshop if it doesn't trigger the right rendering stuff this way.

2024-09-02 13:32 UTC, bctiemann commented on docs/media/screenshots/cable-trace.png
Recaptured this; note that it's taller but also wider, so it can be scaled down 1:1 if it needs to render at a certain height.

2024-09-03 13:03 UTC, jeremystretch approved these changes

2024-09-03 13:03 UTC, merged