Closes #16786: Clone device location from rack
netbox-community/netbox pull request #17508
Opened 2024-09-16 16:26 UTC by alehaa

### Fixes: #16786 

To fix errors when selecting a rack of a child location being not part of the parent location, the site and location are now always copied from the rack when a device is assigned to a rack.

2024-09-16 20:56 UTC, bctiemann approved these changes

2024-09-17 12:48 UTC, jeremystretch requested changes

2024-09-18 18:56 UTC, alehaa commented on netbox/dcim/models/devices.py
> -            })
Thanks for the advice. I've reverted fd309a0 and altered the location check instead.

2024-09-19 17:40 UTC, jeremystretch commented
After re-reading FR #16786 the proposed behavior doesn't seem to be valid. The location to which a device is assigned **must** match the location of its assigned rack (if any); anything else would be invalid.

Please also see my [comment](https://github.com/netbox-community/netbox/issues/16786#issuecomment-2361807863) on the FR as it sounds like your use case is better solved by the introduction of new filters.

2024-11-04 04:03 UTC, closed without merging