Fixes: #17360 - Ensure model is defined when rendering bulk_edit_button
netbox-community/netbox pull request #17535
Opened 2024-09-18 22:44 UTC by bctiemann

### Fixes: #17360

Addresses a common issue in HTMX navigation where the inclusion of a call to `bulk_edit_button` where the param `model` is a string raises an `AttributeError: 'str' object has no attribute '_meta'`.

This fix adds a check for truthiness of `model` before trying to render `{% bulk_edit_button %}` or `{% bulk_delete_button %}` in `table.py`.

2024-09-19 16:30 UTC, arthanson requested changes
I'm not sure this is the correct fix (or might be a partial fix) as I think it might just be masking the underlying issue - if you do the scenario to go to the interface and then click the edit bulk edit button (without having any items selected) you are presented with an empty page instead of a toast as you are without HTMX navigation enabled and I think it might be because of this this change allowing a blank model.

I think (not sure) that we need to find why model isn't getting set and get it set correctly.

2024-09-19 16:35 UTC, bctiemann commented
Yeah, agreed -- this didn't really sit right with me except as a one-liner noninvasive fix. I don't yet quite understand what the underlying issue is or whether model is even supposed to be present, but I'll set this to Draft and keep digging.

2024-09-19 18:28 UTC, bctiemann commented
@arthanson I think the blank page on "no interfaces selected" condition is a separate issue entirely; it has to do with the fact that it's an HTMX request that encounters an error and then gets a `redirect` to the return_url, but because it's in an HTMX container it doesn't properly send the browser back to that URL at the top level. I think that needs to be addressed in a separate bugfix.

To deal with the immediate issue, I've reverted the change to the template and set `model` explicitly in the page context, after investigating more and finding that that variable is being set in a lot of other pages (particularly list views) but not in this `ObjectChildrenView`. It seems to behave correctly now without having to catch the conditional in the template because `model` is not used except in the `{% if request.htmx %}` block.

2024-09-19 18:33 UTC, bctiemann commented
Note that the surface-level error (`model` being interpreted as a `str`) was because the construct `{% bulk_edit_button model query_params=request.GET %}` passes in an unset or missing `model` context variable as an empty string, because it's interpolated as nothing. It's not that `model` is actually a str, it's that it isn't present in the context at all and the template processor just swallows that condition by treating the missing param as a space in the tag.

2024-09-24 14:28 UTC, jeremystretch requested changes
The template `htmx/table.html` is used in several places; this needs to be addressed in all of them. It's probably sufficient to tweak the template to pass `object` to the bulk action button tags, rather than `model`.

2024-09-24 14:31 UTC, bctiemann commented
All the other occurrences of `bulk_action_button` are in list views though. Wouldn't those have an `object_list` rather than an `object`?

2024-09-24 15:31 UTC, bctiemann commented
Passing `self.child_model` (e.g. `Interface`) to the template instead of `model` (e.g. `Device`) seems like the right answer here. The success URL now pushes to the Interfaces tab as is correct.

2024-09-26 19:36 UTC, jeremystretch approved these changes

2024-09-26 19:36 UTC, merged