DRAFT: 17569 Add help text to VLAN Group that is not saved on the interface
netbox-community/netbox pull request #17578
Opened 2024-09-23 18:20 UTC by arthanson

### Fixes: #17569

2024-09-23 18:38 UTC, bctiemann approved these changes

2024-09-24 13:53 UTC, jeremystretch requested changes

2024-09-24 13:53 UTC, jeremystretch commented on netbox/dcim/forms/model_forms.py
> +        help_text=_("Used only to filter tagged and untagged VLANs below. This is not saved on the interface.")
```suggestion
        help_text=_("Filter VLANs available for assignment by group.")
```

2024-09-24 20:49 UTC, jeremystretch approved these changes

2024-09-24 20:49 UTC, merged