17644 fix login icon size
netbox-community/netbox pull request #17730
Opened 2024-10-10 17:41 UTC by arthanson

### Fixes: #17644 

Unfortunately tables sets global height: auto and from https://stackoverflow.com/questions/44010645/remove-height-auto-using-css it doesn't look like it is possible to un-set it in css after the fact (also tried to set it just for the login img in css and it doesn't effect it).  So directly setting the height here seems like the most narrow change that doesn't effect images elsewhere.

2024-10-10 19:56 UTC, bctiemann approved these changes

2024-10-11 12:37 UTC, jeremystretch requested changes

2024-10-11 12:37 UTC, jeremystretch commented on netbox/templates/login.html
> +        <img src="{% static 'logo_netbox_dark_teal.svg' %}" alt="{% trans "NetBox Logo" %}" height="80" class="hide-theme-dark" style="height: 80px;">
We should avoid setting absolute CSS parameters directly on individual elements wherever possible. Let's instead introduce `logo` and `sso-icon` classes for the affected elements, which can be reused and/or tweaked easily if needed.

2024-10-11 18:23 UTC, bctiemann approved these changes

2024-10-11 20:06 UTC, jeremystretch approved these changes

2024-10-11 20:06 UTC, merged