17635 fix script AbortTransaction
netbox-community/netbox pull request #17764
Opened 2024-10-15 20:20 UTC by arthanson

### Fixes: #17635

2024-10-16 17:11 UTC, bctiemann approved these changes

2024-10-16 17:45 UTC, jeremystretch requested changes

2024-10-16 17:45 UTC, jeremystretch commented on netbox/extras/jobs.py
> +            pass
This doesn't need to be caught again; we can just avoid re-raising it on line 52.

2024-10-18 14:55 UTC, jeremystretch approved these changes

2024-10-18 14:55 UTC, merged