Fixes: #17732 - Add a background-color to img elements in docs to ensure readability in dark mode
netbox-community/netbox pull request #17790
Opened 2024-10-16 19:18 UTC by bctiemann

### Fixes: #17732

Adds a `background-color` property to the `img` CSS style for docs, to ensure that PNGs with transparent backgrounds and black text are still readable even on a dark-mode background.

<img width="953" alt="Screenshot 2024-10-16 at 2 18 10 PM" src="https://github.com/user-attachments/assets/86d6e945-a29e-4239-8f99-4344a43a3292">

2024-10-16 20:23 UTC, jeremystretch requested changes
The logo on the main page still needs to be fixed:

![screenshot](https://github.com/user-attachments/assets/07487043-040b-489d-a1e4-5bf649844c24)

2024-10-17 19:11 UTC, bctiemann commented
<img width="789" alt="Screenshot 2024-10-17 at 3 10 21 PM" src="https://github.com/user-attachments/assets/e521c561-aaca-4c60-bafa-cbc223a5e2a6">
<img width="820" alt="Screenshot 2024-10-17 at 3 10 26 PM" src="https://github.com/user-attachments/assets/232f1bb3-f10b-4eed-b3c5-59014587ae59">

2024-10-18 14:28 UTC, jeremystretch commented
Unfortunately I don't think the white outline will comply with our branding rules for the logo. We do have dark & light versions of the logo available, and it looks like mkdocs-material does [support image toggling](https://squidfunk.github.io/mkdocs-material/reference/images/#light-and-dark-mode) for light & dark modes. I'll take a stab at it.

2024-10-18 14:46 UTC, jeremystretch approved these changes

2024-10-18 14:47 UTC, merged