10711 Add Scope to WirelessLAN
netbox-community/netbox pull request #17877
Opened 2024-10-28 21:14 UTC by arthanson

### Fixes: #10711

2024-11-04 19:47 UTC, bctiemann approved these changes

2024-11-05 15:01 UTC, jeremystretch requested changes
The wireless LAN HTML template needs to be extended to show the assigned scope.

This also needs API tests.

2024-11-05 15:01 UTC, jeremystretch commented on netbox/wireless/tests/test_views.py
We should extend the CSV test data to test bulk import assignment as well.

2024-11-07 15:00 UTC, jeremystretch approved these changes
I've extended the CSV test data.

2024-11-07 15:28 UTC, merged