17686 config option for disk divider
netbox-community/netbox pull request #18011
Opened 2024-11-14 08:19 UTC by Haeki

### Fixes: #17686 Ability to select disk divider

I added two new config options to specify the divider used to calculate the disk and ram sizes in different units.
The default value is 1000 but can be changed to 1024 to get GiB instead of GB.
Those config values are used in the `humanize_megabytes` method. I split this method into two separate methods, one for RAM and one for disk values. Additionally I added the disk config value to the disk migration so that users with GiB values get them converted to MiB.
I tested the changes in my local environment and noticed no problems.

I'm open for feedback and I also didn't include any tests yet.

2025-01-29 08:17 UTC, 1358 commented
Would love to see this merged, too.

2025-01-31 00:36 UTC, DanSheps commented
Can you rebase to main?

2025-02-07 02:02 UTC, DanSheps requested changes

2025-02-07 02:04 UTC, DanSheps requested changes, later dismissed

2025-02-07 02:04 UTC, DanSheps commented on netbox/netbox/settings.py
> +RAM_UNIT_DIVISOR = getattr(configuration, 'MEMORY_UNIT_DIVISOR', 1000)
We should have a check in here to verify it is either 1000 or 1024

2025-02-07 09:04 UTC, Haeki commented on netbox/netbox/configuration_example.py
> +RAM_UNIT_DIVISOR = 1024
👍🏼

2025-02-07 17:32 UTC, Haeki commented on netbox/netbox/settings.py
> +RAM_UNIT_DIVISOR = getattr(configuration, 'MEMORY_UNIT_DIVISOR', 1000)
I added a simple check e21e31762799684938b855dc0c4e917c03beec13

2025-02-18 17:08 UTC, arthanson requested changes
These also need to be added to the documentation, configuration/miscellaneous.md

2025-02-18 17:08 UTC, arthanson commented on netbox/netbox/configuration_example.py
> +DISK_BASE_UNIT = 1024
would want these commented out as if you copied this over the default would change.

2025-02-26 00:05 UTC, arthanson commented
@Haeki is this ready for re-review? If so please toggle the re-request review (spinner) in the upper right next to my name.

2025-03-04 17:56 UTC, arthanson requested changes

2025-03-04 17:56 UTC, arthanson commented on netbox/netbox/settings.py
> +RAM_BASE_UNIT = getattr(configuration, 'MEMORY_UNIT_DIVISOR', 1000)
I think this needs to be changed to RAM_BASE_UNIT - I'm not seeing RAM get changed in the display.
![vm4](https://github.com/user-attachments/assets/70d53711-ecf3-4aa1-9410-391934c163de)

2025-03-07 09:58 UTC, Haeki commented on netbox/netbox/settings.py
> +RAM_BASE_UNIT = getattr(configuration, 'MEMORY_UNIT_DIVISOR', 1000)
Seems like my find and replace missed that one. Thanks

2025-03-07 18:30 UTC, arthanson approved these changes

2025-03-07 18:47 UTC, merged