Add status to rack elevation device tooltip
netbox-community/netbox pull request #18083
Opened 2024-11-24 21:44 UTC by rodvand

### Fixes: #18065 

Adds device status in rack elevation tooltip hover.

2024-12-02 15:37 UTC, bctiemann submitted a review, later dismissed

2024-12-02 17:55 UTC, jeremystretch requested changes

2024-12-02 17:55 UTC, jeremystretch commented on netbox/dcim/svg/racks.py
> +    description += f'\nStatus: {device.status.capitalize()}'
Please be sure to use the [`get_FOO_display()` method](https://docs.djangoproject.com/en/5.1/ref/models/instances/#django.db.models.Model.get_FOO_display) for choice fields.
```suggestion
    description += f'\nStatus: {device.get_status_display()}'
```

2024-12-02 17:59 UTC, bctiemann approved these changes

2024-12-05 01:59 UTC, jeremystretch approved these changes

2024-12-05 01:59 UTC, merged