Fixes: #16757 - Use table_htmx.html for assigning ipaddresses
netbox-community/netbox pull request #18226
Opened 2024-12-12 20:51 UTC by bctiemann

### Fixes: #16757

Swaps `inc/table_htmx.html` for `inc/table.html` in the `ipaddress_assign.html` template. This ensures that objects clicked on in that table return a properly targeted HTMX response, whether or not HTMX navigation is turned on.

There are many places where `inc/table.html` is used, but it appears HTMX targeting is not used in those places. As HTMX is rolled out more pervasively, these will all need to be audited.

2024-12-16 15:53 UTC, jeremystretch requested changes
This returns the IP address edit form correctly, however after saving the IP the user is redirected to a bare view of the device's interfaces table.

![screenshot](https://github.com/user-attachments/assets/f281a7aa-1e95-4ab6-8ae3-572839b41933)

2024-12-16 23:56 UTC, bctiemann commented
@jeremystretch Turns out that behavior you're seeing of the subsequent table rendering is happening in develop, it's not related to my fix. I've added another adjustment which lets us `disable_htmx` certain views (currently just `DeviceInterfacesView` because it's special) so that won't happen.

2024-12-17 16:14 UTC, bctiemann commented
Reverted the last commit as the full-page bare-view issue is preexisting and beyond the scope of this specific issue's fix.

2024-12-17 19:46 UTC, jeremystretch approved these changes

2024-12-17 19:46 UTC, merged