Add tenancy to cluster
netbox-community/netbox pull request #3572
Opened 2019-10-07 12:45 UTC by frelon

### Fixes: #3455 

Adds Tenant field to cluster and related forms.

Adds badge to Tenant-view that displays number of related clusters.

Adds filter for tenant on cluster filter.

2019-10-07 14:00 UTC, DanSheps commented
Please correct the PEP8 errors and re-push:

> netbox/virtualization/models.py:107:13: E126 continuation line over-indented for hanging indent
> netbox/virtualization/models.py:108:9: E131 continuation line unaligned for hanging indent
> netbox/virtualization/models.py:109:9: E131 continuation line unaligned for hanging indent
> netbox/virtualization/models.py:110:9: E131 continuation line unaligned for hanging indent
> netbox/virtualization/models.py:111:9: E131 continuation line unaligned for hanging indent

2019-10-15 15:37 UTC, DanSheps requested changes

2019-10-15 15:37 UTC, DanSheps commented on netbox/templates/tenancy/tenant.html
> +                    <h2><a href="{% url 'virtualization:cluster_list' %}?tenant={{ tenant.slug }}" class="btn {% if stats.cluser_count %}btn-primary{% else %}btn-default{% endif %} btn-lg">{{ stats.c
looks like there is a typo here

2019-10-16 06:23 UTC, frelon commented on netbox/templates/tenancy/tenant.html
> +                    <h2><a href="{% url 'virtualization:cluster_list' %}?tenant={{ tenant.slug }}" class="btn {% if stats.cluser_count %}btn-primary{% else %}btn-default{% endif %} btn-lg">{{ stats.c
Nice catch!

2019-10-17 13:44 UTC, DanSheps approved these changes

2019-10-23 15:52 UTC, jeremystretch approved these changes

2019-10-23 15:53 UTC, merged