Fixes: #3950 "Create and Add Another" does retain device type
netbox-community/netbox pull request #3955
Opened 2020-01-18 12:45 UTC by kobayashi

### Fixes: #3950 "Create and Add Another" does retain device type

Add lines to retrieve manufacture pk while `device_type` is provided.

2020-01-21 14:55 UTC, kobayashi commented
found more abstract approach. I will commit it later again.

2020-01-21 20:01 UTC, jeremystretch requested changes

2020-01-21 22:43 UTC, kobayashi commented on netbox/utilities/utils.py
> +    if field_name == 'group':
If we do get manufacturer from device_type in DeviceForm, we need a query like this.
`kwargs['initial']['manufacturer'] = DeviceType.objects.get(pk=kwargs['initial']['device_type']).manufacturer.pk`
I was concerned this made database access inside form in my first commit. If you think it's ok, I will change to the way.

2020-01-23 22:26 UTC, jeremystretch commented on netbox/utilities/utils.py
> +    if field_name == 'group':
Yeah, I think that's fine. Maybe not the most efficient approach but definitely the easiest to support at the moment. I would be cautious of overwriting any existing initial data though. Something like:

```python
if 'manufacturer' not in kwargs['initial']:
    device_type_id = kwargs['initial']['device_type']
    # Return the bare slug, or None
    manufacturer_slug = DeviceType.objects.filter(pk=device_type_id).values_list('manufacturer__slug', flat=True).first()
    kwargs['initial']['manufacturer'] = manufacturer_slug
```

2020-01-24 08:35 UTC, kobayashi commented on netbox/utilities/utils.py
> +    if field_name == 'group':
Modified to get the values in form. Also added test for initial data.

2020-01-24 18:49 UTC, merged