Fix incorrect file references in documentation
netbox-community/netbox pull request #3990
Opened 2020-01-23 02:03 UTC by mikewright

### Fixes: #3961 

updated documentation to reference correct files
copied largely from 3-http-daemon.md

2020-01-23 16:44 UTC, jeremystretch requested changes
I'm fine with fixing the mistakes but let's not gut the examples without further discussion. #3961 pertains only to the correction of errors.

2020-01-23 17:17 UTC, kobayashi requested changes

2020-01-23 17:17 UTC, kobayashi commented on docs/installation/migrating-to-systemd.md
Let us keep the deleted line and add your note lines as supplement.

2020-01-24 06:50 UTC, DanSheps commented
Looking at the PR, it looks like @kobayashi suggestion is all that is needed.  The examples that are in there are from the old systemd configuration that we never used so I think we are fine to remove those as part of this.

2020-01-24 06:54 UTC, DanSheps requested changes

2020-01-24 06:54 UTC, DanSheps commented on docs/installation/migrating-to-systemd.md
> +```
I don't think we need to include this.  Someone who is relatively proficient with systemd will know how to do this and someone who is not won't really know what is going on (beyond the running) and there are other ways to verify that.

2020-01-24 06:54 UTC, DanSheps commented on docs/installation/migrating-to-systemd.md
> -Edit /etc/systemd/system/netbox.service and /etc/systemd/system/netbox-rq.service. Be sure to verify the location of the gunicorn executable on your server (e.g. `which gunicorn`).  If using CentOS/R
We may want to keep the username portion, as it is not always the case that www-data is used or available.  However I would just tack it onto the end.

2020-01-31 15:36 UTC, DanSheps commented
There has been no activity on this for a few days, I am going to close this out and resolve myself as we have had a few issues opened up in the last few days.

2020-01-31 15:36 UTC, closed without merging