Fixes #3886: Config context cluster (group)
netbox-community/netbox pull request #4014
Opened 2020-01-26 10:55 UTC by hSaria

### Fixes: #3886

Added cluster and cluster group to config context.

> I may need to update the migration depending on whether this goes before or after #4013.

2020-02-02 21:49 UTC, kobayashi requested changes

2020-02-02 21:49 UTC, kobayashi commented on netbox/extras/forms.py
> +        queryset=TenantGroup.objects.all(),
This should be `queryset=ClusterGroup.objects.all()`

2020-02-02 21:49 UTC, kobayashi commented on netbox/extras/forms.py
> +        queryset=Tenant.objects.all(),
also `queryset=Cluster.objects.all()`

2020-02-02 23:35 UTC, hSaria commented on netbox/extras/forms.py
> +        queryset=Tenant.objects.all(),
Thanks. I missed during my copy-foo.

2020-02-03 21:02 UTC, jeremystretch approved these changes

2020-02-03 21:02 UTC, merged