Vlan branch
netbox-community/netbox pull request #4186
Opened 2020-02-17 13:10 UTC by Arkasha99

### Fixes: <#4126>

according to issue I added "Show VLANs" button to interface table in device viewpage. It works exactly like "Show IPs" button showing VLANs instead. 
The table looks almost the same as VLANs table in interface viewpage. 
The table has been added to interface.html, script is in js/interface_toggles.

2020-02-17 16:05 UTC, DanSheps requested changes
Once you correct these, I will take another look at it and see how it looks on develop.

Keep in mind though, this might significantly increase the query time for interfaces so we need to do thorough testing.

2020-02-18 08:21 UTC, Shm013 commented on netbox/templates/dcim/inc/interface.html
> -            {# Placeholder #}
extraspaces

2020-02-18 11:45 UTC, Arkasha99 commented on netbox/project-static/js/interface_toggles.js
> +        $('.ipaddresses').hide();
At first i was trying to make the VLANs table working like IPs table (using the tr and its class to hide rows) but it didn't work properly. The script for hiding VLANs table didn't work at all. When I was clicking "show VLANs" Ihad no response (when I had IP and VLAN table at the same time only IP row was hiding). So the reason of changing the script and td class was the only way (as for me) to make it work, and it worked great.

2020-02-18 15:18 UTC, jeremystretch commented
I have marked #4126 as blocked by #4193. Per my comment [here](https://github.com/netbox-community/netbox/issues/4126#issuecomment-587501933) cannot accept any further modifications to the device interfaces list template until it has been refactored substantially.

FYI this is why the pull request template says to wait until an issue has been accepted before submitting any work. Thank you for your contribution, but unfortunately we cannot accept it at this time.

2020-02-18 15:18 UTC, closed without merging