Improve APISelect query parameter handling
netbox-community/netbox pull request #7040
Opened 2021-08-26 07:44 UTC by thatmattlove

### Fixes: #7034, #7035

- Replaced `query_params` on `DynamicModelChoiceMixin` with `filter_fields`, which carries a more strict data model to define how the field's related fields should be handled. The resulting data is serialized to JSON and added as a single `data-filter-fields` attribute on the `<select/>` element, and then appropriately handled in the UI.
- Refactor APISelect TypeScript class to handle new logic — parsing of the `data-filter-fields` into an expected structure seems to be much simpler than the previous method. Or at least, it's easier for me follow :)
- `query_params` is still available on the widget to add **static** values only.
- Restructured former `netbox/project-static/src/select/api.ts` to a directory to break up the 1000+ LOC into multiple files for better readability.
- Fixed #7034 which was primarily broken due to how we've restructured the form layout (we needed to hide the field's parent's parent, not the immediate parent). Secondarily, the `filter_fields` changes also fix the filtering itself.
- Updated `extras.ObjectVar` docs to reflect addition of `filter_fields`.

All the testing I can think to do passes perfectly, from what I can tell.

2021-08-26 14:12 UTC, jeremystretch requested changes

2021-08-28 16:47 UTC, thatmattlove commented
Probably a hella messy commit history, but, this should contain the fixes we discussed. Nutshell: the current `query_params` API is maintained, all the transformation logic occurs in the widget.

2021-08-30 13:42 UTC, jeremystretch approved these changes

2021-08-30 13:43 UTC, jeremystretch commented
Awesome work, thanks @thatmattlove!

2021-08-30 13:43 UTC, merged