Fix #7564: virtual-chassis position zero
netbox-community/netbox pull request #7583
Opened 2021-10-19 14:46 UTC by PieterL75

### Fixes: #7564 

When a new VC was created with a VC start position of zero, it was created with a start position of 1.
When a VC was displayed that had a position of zero, the label was not displayed in the VC overview.

2021-10-19 19:07 UTC, jeremystretch requested changes
Thanks for taking this on!

2021-11-03 13:44 UTC, PieterL75 reviewed
Ok

2021-11-11 16:30 UTC, jeremystretch commented on netbox/dcim/forms/object_create.py
> +            initial_position = self.cleaned_data.get('initial_position') if self.cleaned_data.get('initial_position') != None else 1
@PieterL75 this still needs to be addressed. What is the issue?

2021-11-11 16:40 UTC, PieterL75 commented on netbox/dcim/forms/object_create.py
> +            initial_position = self.cleaned_data.get('initial_position') if self.cleaned_data.get('initial_position') != None else 1
Jeremy,
The proposed solution with .get did not work.
I submitted a new update with the "if self.cleaned_data.get('initial_position') != None else 1".
See below in the pull request

Pieter

2021-11-11 17:09 UTC, jeremystretch commented
Ok, I dug into this a bit and I see why you were getting stuck. The VC creation is missing a piece of validation logic to ensure that `initial_position` is set if adding VC members.

Also, the badge display needed to be fixed by passing `show_empty=True`; casting the value to a string would break its usage elsewhere in the application.

I'm going to push a separate commit which includes the form validation fix just to get this knocked out, but thank you for tackling this! Sorry it took so long.

2021-11-11 17:09 UTC, closed without merging