Fixes: #6925 Interfaces Table - bring back the visual aids from v2.9
netbox-community/netbox pull request #7767
Opened 2021-11-06 19:46 UTC by CironAkono

### Fixes: #6925 Interfaces Table - bring back the visual aids from v2.9

Reduce the need of the columns "Management Only", "Enabled" and "Type" on the Interfaces table by adding some visual aids that were used on past versions (v2.9).

1. Virtual Interfaces are distinguished by row color "primary ".
2. Disabled Interfaces are distinguished by row color "danger".
3. Keep Connected Interfaces distinguished by row color "success".
4. Interface type distinguished by different icons before the interface name:
   - Management Only: wrench
   - LAG: reorder-horizontal
   - Virtual: circle
   - Wireless: wifi
   - Others: ethernet

2021-11-11 15:42 UTC, jeremystretch requested changes
Looks good! Just a couple minor tweaks.

2021-11-11 15:42 UTC, jeremystretch commented on netbox/dcim/tables/devices.py
> +    elif not record.is_connectable:
```suggestion
    elif record.is_virtual:
```

This should evaluate `is_virtual` to accommodate wireless interfaces in v3.1.

2021-11-11 15:42 UTC, jeremystretch commented on netbox/dcim/tables/devices.py
> +    return ''
```suggestion
    return get_cabletermination_row_class(record)
```

2021-11-11 17:29 UTC, merged

2021-11-11 17:29 UTC, jeremystretch commented
Thanks @CironAkono!

2021-11-15 18:38 UTC, DanSheps commented
The visual aids are back!