Add REMOTE_AUTH_AUTOCREATE_GROUPS
netbox-community/netbox pull request #8603
Opened 2022-02-10 12:54 UTC by larsks

When REMOTE_AUTH_AUTOCREATE_GROUPS is True, Netbox will create groups
referenced in the REMOTE_AUTH_GROUP_HEADER that don't exist in the
database.

2022-02-10 14:14 UTC, candlerb commented
The linked issue is #7671 (although not yet accepted)

2022-02-10 15:01 UTC, larsks commented
Sorry, it was linked in the commit message but not the PR description.

2022-03-08 21:56 UTC, larsks commented
I've rebased this on the current `develop` branch.

2022-04-01 19:50 UTC, kkthxbye-code requested changes

2022-04-01 19:50 UTC, kkthxbye-code commented on netbox/netbox/settings.py
> +REMOTE_AUTH_AUTO_CREATE_GROUP = getattr(configuration, 'REMOTE_AUTH_AUTO_CREATE_GROUP', False)
```suggestion
REMOTE_AUTH_AUTO_CREATE_GROUPS = getattr(configuration, 'REMOTE_AUTH_AUTO_CREATE_GROUPS', False)
```

I think you made a copy paste error. When changing it to the above suggestion the PR works as intended.

2022-04-01 19:50 UTC, kkthxbye-code commented on netbox/netbox/settings.py
> +REMOTE_AUTH_AUTO_CREATE_GROUP = getattr(configuration, 'REMOTE_AUTH_AUTO_CREATE_GROUP', False)
You should also add the new setting to the docs.

2022-05-14 14:33 UTC, kkthxbye-code commented
@larsks - are you still interested in finishing this? When my review has been addressed, it should be good to go.

2022-05-18 20:11 UTC, larsks commented
@kkthxbye-code yes, still interested; just ended up with my head in other things for a bit. I'll try submitting an update over the next couple of days.

2022-08-17 04:26 UTC, closed without merging

2022-09-16 04:33 UTC, davama commented
@larsks 
Hope you are well. Would be great to have this feature!
I can help in testing if need be
Thank you for wiping this up

Regards