#8233 Restrict API key usage by source IP
netbox-community/netbox pull request #8865
Opened 2022-03-14 11:40 UTC by PieterL75

### Implements: #8233

2022-03-14 14:37 UTC, jeremystretch requested changes
Looks like a great start! Thanks for taking this on.

2022-03-14 15:22 UTC, PieterL75 commented on docs/configuration/optional-settings.md
> +## PROXY_HEADER_REALIP
I'll put the lines in remark, and create a separate FR for the new config variable name

2022-03-14 17:19 UTC, PieterL75 reviewed
Updating PR with changes

2022-03-15 10:23 UTC, PieterL75 commented
Noticed that I'm merging in the master, rather than the develop branch,,, 
Canceling this PR

2022-03-15 10:23 UTC, closed without merging