Closes #8894: Add first and last name username user api select
netbox-community/netbox pull request #9150
Opened 2022-04-15 21:56 UTC by minitriga

### Fixes: #8894

2022-04-18 16:57 UTC, jeremystretch requested changes

2022-04-18 16:57 UTC, jeremystretch commented on netbox/users/api/nested_serializers.py
> +            return f"{obj.username} ({obj.first_name} {obj.last_name})"
We can use `get_full_name()` on the User instance to return the first and/or last name if either is defined:

```suggestion
        if full_name := obj.get_full_name():
            return f"{obj.username} ({full_name})"
```

2022-04-18 16:57 UTC, jeremystretch commented on netbox/users/api/nested_serializers.py
> +    display = serializers.SerializerMethodField(read_only=True)
This is defined on the `BaseModelSerializer` class.

```suggestion
```

2022-04-18 16:57 UTC, jeremystretch commented on netbox/users/api/nested_serializers.py
> +            return f"{obj.username} ({obj.first_name} {obj.last_name})"
`get_display()` should be defined on `UserSerializer` as well.

2022-05-03 10:43 UTC, minitriga commented
Updated. Cheers for the review. 

Just to note that `get_full_name` will return first and last name individually if the other is not set. 

For example if the first_name is not defined it will only show surname. 

```
>>> User.objects.get(pk=2).first_name
''
>>> User.objects.get(pk=2).last_name
'Gittings'
>>> User.objects.get(pk=2).get_full_name()
'Gittings'
```

2022-05-04 18:09 UTC, merged